---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true

- name: Deploy Nginx reverse proxy config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/fastapi
    mode: '0644'

- name: Enable Nginx site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/fastapi
    dest: /etc/nginx/sites-enabled/fastapi
    state: link
    force: true

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
